name: Deploy
on:
  - workflow_call
  - workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm run build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: notes
          directory: public/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
